#!/usr/bin/env python
"""Harvest a case-insensitive FORM.lower() -> most-frequent-LEMMA lookup table for HYPHENATED
Indonesian forms (reduplication: anak-anak, compounding, etc). Backs id_lemma_case_fix.py's
safety-net override, printed as a Python dict literal to embed directly in that module.

Why this is needed: the trainable_lemmatizer's edit trees are literal-content substitutions
(e.g. delete the literal prefix "Anggota-"), so a capitalised token ("Anggota-anggota") and
its lowercase counterpart ("anggota-anggota") get two DIFFERENT trees even though the correct
lemma is identical. Sentence-initial capitalisation makes every such tree a near-singleton
(one training instance per distinct word), which the classifier cannot reliably learn to
select at inference -- it falls back to leaving the lemma unchanged. Plain (non-hyphenated)
capitalised words are unaffected (they share trees with hundreds of other simple downcasings),
so the table is scoped to hyphenated forms only.

Run: .venv/bin/python scripts/build_id_lemma_lut.py assets_id_coarse_rl/id_gsd-coarse-train.relabeled.conllu
"""
import sys
from collections import Counter, defaultdict

def main():
    inp = sys.argv[1]
    counts = defaultdict(Counter)
    for line in open(inp, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        cols = line.split("\t")
        if len(cols) < 3 or not cols[0].isdigit():
            continue
        form, lemma = cols[1], cols[2]
        if lemma == "_" or "-" not in form:
            continue
        # keep only genuine hyphenated wordforms (reduplication/compounding) -- skip numbers,
        # URLs, and stray punctuation runs that also contain a hyphen.
        if not form.replace("-", "").isalpha():
            continue
        # a handful of GSD gold rows have a stray XPOS/Morf fragment leaked into the LEMMA
        # column (e.g. "multi_F--$DASH^proses") -- skip anything that isn't plain wordform text.
        if any(c in lemma for c in "$^_"):
            continue
        counts[form.lower()][lemma] += 1

    print("# generated by scripts/build_id_lemma_lut.py -- do not edit by hand")
    print("ID_HYPHEN_LEMMA_LUT = {")
    for key in sorted(counts):
        lemma, _ = counts[key].most_common(1)[0]
        print(f"    {key!r}: {lemma!r},")
    print("}")
    print(f"{len(counts)} distinct hyphenated forms", file=sys.stderr)

if __name__ == "__main__":
    main()
