#!/usr/bin/env python3
"""Harvest the raising-frame table that `sud_subject_rule` reads, and write it as a Python module.

Two tables per language, both derived from the TRAIN split only (so a test evaluation of the rule
is honest):

  FRAMES[lang]  (head lemma, deprel, head UPOS) triples where a `Subject=` feature is the majority
                outcome. A frame fires when the context occurs at least `--min-count` times in
                train and carries `Subject=` on at least `--threshold` of them.
  VALUES[lang]  (deprel, head UPOS) -> the majority `Subject=` value. This side is effectively
                deterministic: 100% in en/fa/la/sa/yue, 91% in zh.

Same shape as `build_id_lemma_lut.py`: the output is a literal-dict module the component imports,
so the shipped wheel carries no data files.

    build_sud_subject_frames.py --out scripts/sud_subject_frames.py
"""
import argparse
import collections
import json

# The train split each released arm actually uses.
TRAIN = {
    "en":  "assets/en_ewt-sud-train.relabeled_ext.conllu",
    # en_gum: the second English arm (EWT + the ten non-NonCommercial GUM genres).
    # A separate key, not a replacement -- `en` must keep pointing at the EWT-only files
    # that the released CC BY-SA en_sud_ewt wheel was built from.
    "en_gum": "assets/en_ewtgum-sud-train.relabeled_ext.conllu",
    "zh":  "assets_zh/SUD_Chinese-GSDBoth/zh_gsdboth-sud-train.relabeled_ext.conllu",
    "yue": "assets_yue/SUD_Cantonese-HK/yue_hk-sud-train.relabeled_ext.conllu",
    "lzh": "assets_lzh/SUD_Classical_Chinese-Kyoto-Both/lzh_kyotoboth-sud-train.relabeled_ext.conllu",
    "fa":  "assets_fa/SUD_Persian-PerDT/fa_perdt-sud-train.relabeled_ext.conllu",
    "la":  "assets_la/la_ittbproiel-sud-train.relabeled_ext.conllu",
    # csl_mwt, not csl_rev: the DCS/MWT generation. `corpus_sa_csl_rev` is the SUPERSEDED pausa-normalised representation (CLAUDE.md lists `rebuild_sa_csl_rev.sh` under "Superseded but kept"); its FORMs and tokenisation differ from the arm that ships, and it is UNRELABELLED (`udep` 7.89 % of tokens against 0.00 %). See the BUILD PROVENANCE table in docs/sanskrit.md.
    "sa":  "corpus_sa_mwt_rl2/train.csl_mwt.conllu",
}


def sentences(path):
    block = []
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line:
            if block:
                yield block
            block = []
            continue
        if line.startswith("#"):
            continue
        f = line.split("\t")
        if "-" in f[0] or "." in f[0]:
            continue
        block.append(f)
    if block:
        yield block


def misc_get(col, key):
    for item in col.split("|"):
        if item.startswith(key + "="):
            return item.split("=", 1)[1]
    return None


def harvest(path, threshold, min_count):
    stat = collections.defaultdict(lambda: [0, 0])       # (lemma, deprel, hpos) -> [hits, total]
    values = collections.defaultdict(collections.Counter)  # (deprel, hpos) -> value counts
    for rows in sentences(path):
        index = {f[0]: f for f in rows}
        for f in rows:
            head = index.get(f[6])
            if head is None:
                continue
            key = (head[2], f[7], head[3])
            stat[key][1] += 1
            value = misc_get(f[9], "Subject")
            if value:
                stat[key][0] += 1
                values[(f[7], head[3])][value] += 1
    frames = sorted(k for k, (hits, total) in stat.items()
                    if total >= min_count and hits / total >= threshold)
    best = {"\t".join(k): c.most_common(1)[0][0] for k, c in values.items()}
    return frames, best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="scripts/sud_subject_frames.py")
    ap.add_argument("--threshold", type=float, default=0.5)
    ap.add_argument("--min-count", type=int, default=2)
    args = ap.parse_args()

    all_frames, all_values = {}, {}
    for lang, path in TRAIN.items():
        try:
            frames, values = harvest(path, args.threshold, args.min_count)
        except FileNotFoundError:
            print(f"  {lang}: missing {path} -- skip")
            continue
        all_frames[lang] = [list(k) for k in frames]
        all_values[lang] = values
        print(f"  {lang}: {len(frames)} frames, {len(values)} value contexts")

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write('"""Raising frames for `sud_subject_rule`. GENERATED by '
                 'scripts/build_sud_subject_frames.py -- do not edit by hand.\n\n'
                 'FRAMES[lang]: (head lemma, deprel, head UPOS) contexts where `Subject=` is the\n'
                 'majority outcome in the training split.\n'
                 'VALUES[lang]: "deprel\\thead UPOS" -> the majority `Subject=` value.\n"""\n')
        fh.write("FRAMES = " + json.dumps(all_frames, ensure_ascii=False, indent=1) + "\n\n")
        fh.write("VALUES = " + json.dumps(all_values, ensure_ascii=False, indent=1) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
